### ISSUE TITLE
[Bug]: Executable is not signed !

### ISSUE THREAD

**Issue by aadrian** [massCodeIO/massCode#397] opened 2023-08-02 14:26 UTC
### Describe the bug

The Executable (at least for Windows) is not signed, and as such it is rejected by SmartScreen in most environments.

### To reproduce

1. Use a Windows 10/11 where SmartScreen is active (most environments)
2. Try to start the installer
3. A SmartScreen warning is displayed. The user can only close it, and thus not install MassCode.

### Version

v3.7.0

### OS

Windows 10 and 11

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment] 2023-08-02 15:07
Duplicate of #110

**Closed by antonreshetov** 2023-08-02 15:07 UTC
Labels: pending triage
