### ISSUE TITLE
[Bug]: Apple cannot find a valid certificate for the app.

### ISSUE THREAD

**Issue by leandrodaf** [massCodeIO/massCode#212] opened 2022-08-09 19:27 UTC
### Describe the bug

Apple cannot find a valid certificate for the app.

![image](https://user-images.githubusercontent.com/12107458/183744533-b34a4f32-c217-44b5-be3a-468f3110ab02.png)

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..

### Version

v3.1.0

### OS

macOS - MacBook Pro (16-inch, 2021) - Apple M1 Pro

### Validations

- [X] Follow our [Code of Conduct](https://github.com/massCodeIO/massCode/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/massCodeIO/massCode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/massCodeIO/massCode/discussions).

**Comment by antonreshetov** [comment] 2022-08-09 20:29
Duplicate of #124

**Closed by antonreshetov** 2022-08-09 20:29 UTC
Labels: pending triage
